framework:
  github: amirfaramarzi/tower
  version: 1.14

  files:
    - .env

  extensions:
    - redis

  engines:
    - workerman

  bootstrap:
    - mkdir storage/logs -p

  command: php server.php start
