framework:
  github: sanic-org/sanic
  version: 21.9

  engines:
    - sanic
    - gunicorn
    - uvicorn
    - hypercorn
    - daphne

language:
  engines:
    sanic:
      command: python server.py
